project_id = "gpxrhcnodspjdgolnqeb"

[functions.chat]
verify_jwt = false

[functions.translate-sign]
verify_jwt = false

[functions.describe-visual]
verify_jwt = false

[functions.analyze-emotion]
verify_jwt = false

[functions.scan-accessibility]
verify_jwt = false

[functions.community-posts]
verify_jwt = false

[functions.clean-link]
verify_jwt = false

[functions.translate-language]
verify_jwt = false

[functions.sign-language-query]
verify_jwt = false